#Accelerometers
accelerometer_noise_density: 2.0332145255286385e-02   #Noise density (continuous-time)
accelerometer_random_walk:   7.6256964118535562e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     2.5726753648003466e-03   #Noise density (continuous-time)
gyroscope_random_walk:       4.1701751421755547e-05   #Bias random walk

rostopic:                    /imu      #the IMU ROS topic
update_rate:                 200.0      #Hz (for discretization of the values above)
