#Accelerometers
accelerometer_noise_density: 1.1064727202063160e-02   #Noise density (continuous-time)
accelerometer_random_walk:   4.0436710671970218e-04   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     5.5615003707908009e-04   #Noise density (continuous-time)
gyroscope_random_walk:       2.1248567802952673e-05   #Bias random walk

rostopic:                    /imu      #the IMU ROS topic
update_rate:                 100.0      #Hz (for discretization of the values above)